version: "3.8"

# Docker Volume (データを永続的に保存できるようにする仕組み)
volumes:
    mysql-volume:

services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./src/:/var/www/html
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_NAME}
            - DB_USERNAME=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}

    web:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - ${WEB_PORT}:80
        depends_on:     # コンテナ間の依存関係(先に起動するコンテナのサービス名) PHP->Nginxの順でコンテナを起動
            - app
        volumes:
            - ./src/:/var/www/html

    db:
        build:
            context: .
            dockerfile: ./docker/mysql/Dockerfile
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        # TZ: "Asia/Tokyo"
        volumes:
            - mysql-volume:/var/lib/mysql

    mailhog:
        image: mailhog/mailhog
        ports: 
            - "8025:8025"
